apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: s2i-build-and-deploy
  namespace: pipeline-demo
spec:
  params:
    - default: 'ttl.sh/webapp-log4j-s2i:24h'
      name: IMAGE_NAME
      type: string
    - default: 'http://gogs.gogs.svc.cluster.local:3000/developer/rhacs-app-demo.git'
      name: GIT_REPO
      type: string
    - default: main
      name: GIT_REVISION
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: 'false'
        - name: SKIP_PUSH
          value: ''
        - name: PATH_CONTEXT
          value: src/webapp
        - name: MAVEN_CLEAR_REPO
          value: 'true'
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: s2i-java
      workspaces:
        - name: source
          workspace: workspace
    - name: stackrox-image-scan
      params:
        - name: rox_central_endpoint
          value: roxsecrets
        - name: rox_api_token
          value: roxsecrets
        - name: rox_image
          value: 'quay.io/stackrox-io/roxctl:4.0.2'
        - name: image
          value: $(params.IMAGE_NAME)
        - name: output_format
          value: table
        - name: insecure-skip-tls-verify
          value: 'true'
      runAfter:
        - build
      taskRef:
        kind: Task
        name: stackrox-image-scan
    - name: stackrox-image-check
      params:
        - name: rox_central_endpoint
          value: roxsecrets
        - name: rox_api_token
          value: roxsecrets
        - name: rox_image
          value: 'quay.io/stackrox-io/roxctl:4.0.2'
        - name: image
          value: $(params.IMAGE_NAME)
        - name: output_format
          value: table
        - name: insecure-skip-tls-verify
          value: 'true'
      runAfter:
        - stackrox-image-scan
      taskRef:
        kind: Task
        name: stackrox-image-check
    - name: update-webapp-deployment
      params:
        - name: SCRIPT
          value: oc -n frontend set image deployment/webapp webapp=$(params.IMAGE_NAME)
        - name: VERSION
          value: latest
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: workspace
      runAfter:
        - stackrox-image-check
  workspaces:
    - name: workspace

